name: "Update Nix channels"
on:
  schedule:
  - cron: '43 1 * * 1'
  workflow_dispatch:
jobs:
  update-nix-channels:
    strategy:
      # To avoid git push overlaps
      max-parallel: 1
      matrix:
        channel:
        - stable
        - unstable

    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix-shell --command 'niv update test-${{ matrix.channel }}'
    - run: nix-build tests -A ${{ matrix.channel }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: github.repository == 'ivan-timokhin/nixwebtest'
      with:
        commit_message: 'Update nix channel ${{ matrix.channel }}'
        file_pattern: nix/sources.json
        commit_user_name: GitHub Actions [bot]
